[build]
target = "index.html"
dist = "dist"
release = false

[watch]
ignore = ["dist", "target"]

[serve]
address = "127.0.0.1"
port = 8080
open = false

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "touch ${TRUNK_STAGING_DIR}/.nojekyll; cp sounds.html ${TRUNK_STAGING_DIR}/sounds.html; cp CNAME ${TRUNK_STAGING_DIR}/CNAME"]
